const mongoose=require("mongoose")

const detailSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true,
    },
    fname:{
        type:String,
        required:true,
    },
    lname:{
        type:String,
        required:true
    },
    role:{
        type:String,
        required:true
    },
    linkedin:{
        type:String,
        required:true
    },
    github:{
        type:String,
        required:true
    },
    resume:{
        type:String,
        required:true
    },
    photo:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    aboutDescription:{
        type:String,
        required:true
    },
    aboutImg:{
        type:String,
        required:true
    },
    mobile:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    }
})
const Detail=mongoose.model("Detail",detailSchema)
module.exports=Detail